/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

//#line  14 "test/small1/ll-app.c"
struct ll_node {
   struct ll_node *next ;
};
//#line  18
extern void malloc(void **__fst_ret , unsigned int size ) ;
//#line  19
extern void free(void *p ) ;
//#line  20
extern void _fst_assume_null(void *p ) ;
//#line  25 "test/small1/ll-app.c"
void append(struct ll_node **__fst_ret , struct ll_node *l1 , struct ll_node *l2 ) 
{ 

  {
//#line  27
  if ((unsigned int )l1 == (unsigned int )((struct ll_node *)0)) {
//#line  28
    _fst_assume_null((void *)l1);
    {
//#line  29
    *__fst_ret = l2;
//#line  29
    return;
    }
  } else {
//#line  31
    append(& l1->next, l1->next, l2);
    {
//#line  32
    *__fst_ret = l1;
//#line  32
    return;
    }
  }
}
}
//#line  36 "test/small1/ll-app.c"
void make_list(struct ll_node **__fst_ret , unsigned int n ) 
{ unsigned int i ;
  struct ll_node *ret ;
  struct ll_node *tmp ;
  void *tmp___0 ;
  void **__vericon_ptr_tmp___0 ;

  {
//#line  36
  __vericon_ptr_tmp___0 = & tmp___0;
//#line  38
  i = 0U;
//#line  39
  ret = (struct ll_node *)'\000';
//#line  40
  tmp = (struct ll_node *)'\000';
//#line  41
  i = 0U;
//#line  41
  while (i < n) {
//#line  42
    malloc(__vericon_ptr_tmp___0, sizeof(struct ll_node ));
//#line  42
    tmp = (struct ll_node *)*__vericon_ptr_tmp___0;
//#line  43
    tmp->next = ret;
//#line  44
    ret = tmp;
//#line  41
    i ++;
  }
  {
//#line  46
  *__fst_ret = ret;
//#line  46
  return;
  }
}
}
//#line  49 "test/small1/ll-app.c"
void free_list(struct ll_node *l ) 
{ struct ll_node *p ;
  struct ll_node *tmp ;

  {
//#line  51
  p = l;
//#line  52
  while ((unsigned int )p != (unsigned int )((struct ll_node *)0)) {
//#line  53
    tmp = p->next;
//#line  54
    free((void *)p);
//#line  55
    p = tmp;
  }
//#line  57
  _fst_assume_null((void *)p);
//#line  58
  return;
}
}
//#line  60 "test/small1/ll-app.c"
void main(int *__fst_ret , int argc , char **argv ) 
{ struct ll_node *tmp ;
  struct ll_node *tmp___0 ;
  struct ll_node *tmp___1 ;
  struct ll_node **__vericon_ptr_tmp ;
  struct ll_node **__vericon_ptr_tmp___0 ;
  struct ll_node **__vericon_ptr_tmp___1 ;

  {
//#line  60
  __vericon_ptr_tmp = & tmp;
//#line  60
  __vericon_ptr_tmp___0 = & tmp___0;
//#line  60
  __vericon_ptr_tmp___1 = & tmp___1;
//#line  62
  make_list(__vericon_ptr_tmp, 5U);
//#line  62
  make_list(__vericon_ptr_tmp___0, 5U);
//#line  62
  append(__vericon_ptr_tmp___1, *__vericon_ptr_tmp___0, *__vericon_ptr_tmp);
//#line  62
  free_list(*__vericon_ptr_tmp___1);
  {
//#line  63
  *__fst_ret = 0;
//#line  63
  return;
  }
}
}
